name: release to github packages
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'

      - name: gradle build
        uses: gradle/gradle-build-action@v2.4.0
        with:
          gradle-version: current
          arguments: build

      - name: publish to github maven repo
        env:
          GIT_TERMINAL_PROMPT: 0
        run: |
          cd ./lib
          echo clone maven repo
          git clone https://${{ github.actor }}:${{secrets.MAVEN_REPO}}@github.com/ElisaMin/MavenTest.git build/maven-repo
          echo publish to maven repo
          ./gradlew publishAllPublicationsToTestRepository
          echo push to maven repo
          cd build/maven-repo
          tree
          git config --global user.email "heizi@lge.fun"
          git config --global user.name "action auto commit"
          echo config done
          git add .
          echo commiting
          git commit -m "update maven repo by github action"
          echo pushing
          git push
          echo done

      - name: publish to github packages
        uses: gradle/gradle-build-action@v2.4.0
        with:
          gradle-version: current
          arguments: publish
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.PACKAGE }}